name: CD

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  NODE_VERSION: 24
  VPS_STATIC_PATH: /var/web-apps/mines.mellonis.ru

jobs:
  vps-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
      - name: Build
        run: npm run build
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Sync to VPS
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./dist/ \
            "$SSH_USER@$SSH_HOST:${{ env.VPS_STATIC_PATH }}/"
